#!/usr/bin/env python3
"""
ats_hygiene.py: the only way a packet document gets written to disk.

python-docx's default template stamps every file it saves with
creator "python-docx", description "generated by python-docx", a 2013
creation date, a blank-page thumbnail, a word count of zero, and a
Symbol-font private-use bullet (U+F0B7). LibreOffice copies the author into
the PDF's Info dictionary and XMP. None of that is a parsing problem, but it
is an automation fingerprint on a document whose whole job is to read as
the candidate's own.

write_document() fixes all of it, saves the .docx, verifies the saved file,
renders the PDF with LibreOffice, verifies the PDF, and writes an
upload-named copy (for example Dylan_Winckler_Resume.pdf). build_docs.py
must call write_document() for every document and never call doc.save().

What it sets is what a normal word processor writes: the candidate as
author and last editor, a plain title, the real save time, real word
counts. It does not blank fields and it does not touch the PDF's
Producer/Creator ("LibreOffice ..." / "Writer"), which are true.

CLI, for packets built before this module existed (rewrites metadata and
bullets only, never text):

    python .claude/skills/resume-tailor/scripts/ats_hygiene.py --check output/Acme_12
    python .claude/skills/resume-tailor/scripts/ats_hygiene.py --fix output/Acme_12
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from docx import Document
from docx.oxml.ns import qn
from lxml import etree

BULLET = "\u2022"
PUA_BULLET = "\uf0b7"
TOOL_MARKERS = (b"python-docx",)
THUMBNAIL_RELTYPE = "http://schemas.openxmlformats.org/package/2006/relationships/metadata/thumbnail"
APP_NS = "http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"
KINDS = {"resume": "Resume", "cover_letter": "Cover Letter"}
SOFFICE_FALLBACKS = (
    r"C:\Program Files\LibreOffice\program\soffice.exe",
    r"C:\Program Files (x86)\LibreOffice\program\soffice.exe",
    "/Applications/LibreOffice.app/Contents/MacOS/soffice",
)


class HygieneError(RuntimeError):
    """A written document still carries a generator fingerprint."""


# ---------------------------------------------------------------- naming
def file_stem(candidate: dict) -> str:
    """'Dylan Thomas Winckler' -> 'Dylan_Winckler' (override with candidate.file_stem)."""
    if candidate.get("file_stem"):
        return str(candidate["file_stem"])
    parts = [re.sub(r"[^A-Za-z0-9-]", "", p) for p in str(candidate["name"]).split()]
    parts = [p for p in parts if p]
    return "_".join([parts[0], parts[-1]] if len(parts) > 1 else parts)


def upload_name(candidate: dict, kind: str) -> str:
    return f"{file_stem(candidate)}_{KINDS[kind].replace(' ', '_')}.pdf"


# ---------------------------------------------------------------- docx fixes
def scrub_metadata(doc, name: str, title: str) -> None:
    cp = doc.core_properties
    now = datetime.now(timezone.utc).replace(microsecond=0)
    cp.author = name
    cp.last_modified_by = name
    cp.title = title
    cp.comments = ""
    cp.subject = ""
    cp.keywords = ""
    cp.category = ""
    cp.created = now
    cp.modified = now
    cp.revision = 1


def real_bullets(doc, font: str = "Calibri") -> None:
    """Swap the Symbol-font private-use bullet for U+2022 in the body font."""
    numbering_part = doc.part.numbering_part
    if numbering_part is None:
        return
    for lvl in numbering_part.element.iter(qn("w:lvl")):
        fmt = lvl.find(qn("w:numFmt"))
        if fmt is None or fmt.get(qn("w:val")) != "bullet":
            continue
        text = lvl.find(qn("w:lvlText"))
        if text is not None:
            text.set(qn("w:val"), BULLET)
        rpr = lvl.find(qn("w:rPr"))
        fonts = rpr.find(qn("w:rFonts")) if rpr is not None else None
        if fonts is not None:
            for attr in ("w:ascii", "w:hAnsi", "w:cs"):
                fonts.set(qn(attr), font)


def drop_thumbnail(doc) -> None:
    """The template ships a blank-page thumbnail that file browsers show instead of the resume."""
    rels = doc.part.package.rels
    for rid, rel in list(rels.items()):
        if rel.reltype == THUMBNAIL_RELTYPE:
            rels.pop(rid)


def real_counts(doc) -> None:
    """Replace the template's zero word and character counts with the document's own."""
    app = next((p for p in doc.part.package.iter_parts() if str(p.partname) == "/docProps/app.xml"), None)
    if app is None:
        return
    text = "\n".join(p.text for p in doc.paragraphs if p.text.strip())
    counts = {
        "Words": len(text.split()),
        "Characters": len(re.sub(r"\s", "", text)),
        "CharactersWithSpaces": len(text.replace("\n", " ")),
        "Paragraphs": sum(1 for p in doc.paragraphs if p.text.strip()),
    }
    root = etree.fromstring(app.blob)
    for tag, value in counts.items():
        el = root.find(f"{{{APP_NS}}}{tag}")
        if el is not None:
            el.text = str(value)
    app._blob = etree.tostring(root, xml_declaration=True, encoding="UTF-8", standalone=True)


def clean(doc, candidate: dict, kind: str) -> None:
    name = candidate["name"]
    scrub_metadata(doc, name, f"{name} {KINDS[kind]}")
    real_bullets(doc)
    drop_thumbnail(doc)
    real_counts(doc)


# ---------------------------------------------------------------- verify
def verify_docx(path: Path) -> list[str]:
    doc = Document(path)
    problems = []
    cp = doc.core_properties
    for field in ("author", "last_modified_by", "comments", "title", "subject", "keywords"):
        if "python-docx" in (getattr(cp, field) or "").lower():
            problems.append(f"{path.name}: core property {field} = {getattr(cp, field)!r}")
    if cp.created and cp.created.year < 2020:
        problems.append(f"{path.name}: created date {cp.created:%Y-%m-%d} is the template's")
    uses_bullets = any(p._p.pPr is not None and p._p.pPr.numPr is not None or "List" in p.style.name
                       for p in doc.paragraphs if p.text.strip())
    numbering = doc.part.numbering_part.element.xml if doc.part.numbering_part is not None else ""
    if uses_bullets and PUA_BULLET in numbering:
        problems.append(f"{path.name}: bullets use the private-use glyph U+F0B7")
    if any(r.reltype == THUMBNAIL_RELTYPE for r in doc.part.package.rels.values()):
        problems.append(f"{path.name}: template thumbnail still embedded")
    return problems


def verify_pdf(path: Path) -> list[str]:
    if not path.exists():
        return []
    raw = path.read_bytes()
    problems = [f"{path.name}: contains {m.decode()!r}" for m in TOOL_MARKERS if m in raw]
    try:  # optional, reads compressed metadata too
        from pypdf import PdfReader
        author = (PdfReader(path).metadata or {}).get("/Author") or ""
        if "python-docx" in author and not problems:
            problems.append(f"{path.name}: PDF Author = {author!r}")
    except Exception:
        pass
    return problems


# ---------------------------------------------------------------- write
def soffice() -> str | None:
    found = shutil.which("soffice") or shutil.which("soffice.com")
    if found:
        return found
    return next((p for p in SOFFICE_FALLBACKS if Path(p).exists()), None)


def render_pdf(docx_path: Path) -> Path | None:
    exe = soffice()
    if not exe:
        print(f"[skip pdf] LibreOffice not found; {docx_path.name} left as .docx only")
        return None
    subprocess.run([exe, "--headless", "--convert-to", "pdf", "--outdir", str(docx_path.parent),
                    str(docx_path)], check=True, capture_output=True)
    return docx_path.with_suffix(".pdf")


def write_document(doc, path: Path, candidate: dict, kind: str, pdf: bool = True) -> dict:
    """Clean, save, verify, render, verify, copy. Raises HygieneError on any leftover fingerprint."""
    if kind not in KINDS:
        raise ValueError(f"kind must be one of {sorted(KINDS)}")
    path = Path(path)
    clean(doc, candidate, kind)
    doc.save(path)
    problems = verify_docx(path)
    out = {"docx": path, "pdf": None, "upload": None}
    if pdf:
        out["pdf"] = render_pdf(path)
        if out["pdf"]:
            problems += verify_pdf(out["pdf"])
            out["upload"] = path.parent / upload_name(candidate, kind)
            shutil.copyfile(out["pdf"], out["upload"])
    if problems:
        raise HygieneError("; ".join(problems))
    for key in ("docx", "pdf", "upload"):
        if out[key]:
            print(f"[{key}] {_rel(out[key])}")
    return out


def _rel(path: Path) -> str:
    try:
        return str(Path(path).resolve().relative_to(Path.cwd().resolve()))
    except ValueError:
        return str(path)


# ---------------------------------------------------------------- cli
def _candidate(root: Path) -> dict:
    import yaml
    data = yaml.safe_load((root / "data" / "master_bullets.yaml").read_text(encoding="utf-8"))
    return data["candidate"]


def _utf8_stdout() -> None:
    """Posting text is arbitrary Unicode; a Windows pipe defaults to cp1252."""
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", metavar="PACKET_DIR")
    mode.add_argument("--fix", metavar="PACKET_DIR")
    ap.add_argument("--root", default=".", help="repo root (default: cwd)")
    a = ap.parse_args()
    _utf8_stdout()
    root = Path(a.root)
    pkt = root / (a.check or a.fix)
    problems = []
    for kind in KINDS:
        docx_path = pkt / f"{kind}.docx"
        if not docx_path.exists():
            continue
        if a.fix:
            write_document(Document(docx_path), docx_path, _candidate(root), kind)
        problems += verify_docx(docx_path) + verify_pdf(docx_path.with_suffix(".pdf"))
    print("\n".join(problems) if problems else f"{pkt}: clean")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
