# Support the author by using the funding links below
# Devloped and maintained by Dylan Winckler
# GitHub Sponsors: https://github.com/sponsors/Winkz0
# Buy me a Coffee: https://buymeacoffee.com/Winkz0

github: Winkz0
buy_me_a_coffee: Winkz0

# TY!
